name: mysaas


services:
  redis:
    image: redis:7-alpine
    container_name: mysaas-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - mysaas-redis-data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: mysaas-redisinsight
    ports:
      - "8001:5540"
    depends_on:
      - redis

volumes:
  mysaas-redis-data: