// theme.config.js
import { THEME_IDS } from '../theme/theme.constant.js';

export const themeProfiles = {
    [THEME_IDS.DEFAULT]: {
        name: "Default",
        tier: "free",
        mode: {
            light: {
                "--background": "#ffffff",
                "--foreground": "#09090b",
                "--card": "#ffffff",
                "--card-foreground": "#09090b",
                "--popover": "#ffffff",
                "--popover-foreground": "#09090b",
                "--primary": "#18181b",
                "--primary-foreground": "#fafafa",
                "--secondary": "#f4f4f5",
                "--secondary-foreground": "#18181b",
                "--muted": "#f4f4f5",
                "--muted-foreground": "#71717a",
                "--accent": "#f4f4f5",
                "--accent-foreground": "#18181b",
                "--destructive": "#ef4444",
                "--success": "#22c55e",
                "--warning": "#f59e0b",
                "--border": "#e4e4e7",
                "--input": "#e4e4e7",
                "--ring": "#18181b",
                "--radius": "0.5rem",
                "--sidebar": "#ffffff",
                "--sidebar-foreground": "#18181b",
                "--sidebar-primary": "#18181b",
                "--sidebar-primary-foreground": "#fafafa",
                "--sidebar-accent": "#f4f4f5",
                "--sidebar-accent-foreground": "#18181b",
                "--sidebar-border": "#e4e4e7",
                "--sidebar-ring": "#18181b",
            },
            dark: {
                "--background": "#09090b",
                "--foreground": "#fafafa",
                "--card": "#09090b",
                "--card-foreground": "#fafafa",
                "--popover": "#09090b",
                "--popover-foreground": "#fafafa",
                "--primary": "#fafafa",
                "--primary-foreground": "#18181b",
                "--secondary": "#27272a",
                "--secondary-foreground": "#fafafa",
                "--muted": "#27272a",
                "--muted-foreground": "#a1a1aa",
                "--accent": "#27272a",
                "--accent-foreground": "#fafafa",
                "--destructive": "#dc2626",
                "--success": "#14532d",
                "--warning": "#78350f",
                "--border": "#27272a",
                "--input": "#27272a",
                "--ring": "#d4d4d8",
                "--radius": "0.5rem",
                "--sidebar": "#09090b",
                "--sidebar-foreground": "#fafafa",
                "--sidebar-primary": "#fafafa",
                "--sidebar-primary-foreground": "#18181b",
                "--sidebar-accent": "#27272a",
                "--sidebar-accent-foreground": "#fafafa",
                "--sidebar-border": "#27272a",
                "--sidebar-ring": "#d4d4d8",
            }
        }
    },
    [THEME_IDS.OCEAN_TEAL]: {
        name: "Ocean Teal",
        tier: "pro",
        mode: {
            light: {
                "--background": "#f2fffd",
                "--foreground": "#102a2a",

                "--card": "#ffffff",
                "--card-foreground": "#102a2a",

                "--popover": "#ffffff",
                "--popover-foreground": "#102a2a",

                "--primary": "#0f766e",
                "--primary-foreground": "#ffffff",

                "--secondary": "#d7f5f1",
                "--secondary-foreground": "#134e4a",

                "--muted": "#ecfdfb",
                "--muted-foreground": "#5b8f8a",

                "--accent": "#14b8a6",
                "--accent-foreground": "#ffffff",

                "--destructive": "#dc2626",
                "--success": "#059669",
                "--warning": "#d97706",

                "--border": "#c7ebe6",
                "--input": "#dff7f3",
                "--ring": "#14b8a6",

                "--radius": "0.75rem",

                "--sidebar": "#fcfffe",
                "--sidebar-foreground": "#102a2a",

                "--sidebar-primary": "#0f766e",
                "--sidebar-primary-foreground": "#ffffff",

                "--sidebar-accent": "#e6faf7",
                "--sidebar-accent-foreground": "#134e4a",

                "--sidebar-border": "#c7ebe6",
                "--sidebar-ring": "#14b8a6",
            },

            dark: {
                "--background": "#071c1c",
                "--foreground": "#d7fffa",

                "--card": "#0b2626",
                "--card-foreground": "#d7fffa",

                "--popover": "#0b2626",
                "--popover-foreground": "#d7fffa",

                "--primary": "#2dd4bf",
                "--primary-foreground": "#06201f",

                "--secondary": "#123837",
                "--secondary-foreground": "#d7fffa",

                "--muted": "#102f2e",
                "--muted-foreground": "#7dd3c7",

                "--accent": "#14b8a6",
                "--accent-foreground": "#ecfeff",

                "--destructive": "#dc2626",
                "--success": "#065f46",
                "--warning": "#92400e",

                "--border": "#184544",
                "--input": "#123837",
                "--ring": "#2dd4bf",

                "--radius": "0.75rem",

                "--sidebar": "#0b2626",
                "--sidebar-foreground": "#d7fffa",

                "--sidebar-primary": "#2dd4bf",
                "--sidebar-primary-foreground": "#06201f",

                "--sidebar-accent": "#123837",
                "--sidebar-accent-foreground": "#d7fffa",

                "--sidebar-border": "#184544",
                "--sidebar-ring": "#2dd4bf",
            }
        }
    },
    [THEME_IDS.MIDNIGHT_VIOLET]: {
        name: "Midnight Violet",
        tier: "pro",
        mode: {
            light: {
                "--background": "#faf9ff",
                "--foreground": "#160b2e",
                "--card": "#ffffff",
                "--card-foreground": "#160b2e",
                "--popover": "#ffffff",
                "--popover-foreground": "#160b2e",
                "--primary": "#6d28d9",
                "--primary-foreground": "#ffffff",
                "--secondary": "#ede9fe",
                "--secondary-foreground": "#160b2e",
                "--muted": "#f5f3ff",
                "--muted-foreground": "#7c7c8a",
                "--accent": "#8b5cf6",
                "--accent-foreground": "#ffffff",
                "--destructive": "#ef4444",
                "--success": "#10b981",
                "--warning": "#f59e0b",
                "--border": "#e4e4e7",
                "--input": "#e4e4e7",
                "--ring": "#6d28d9",
                "--radius": "0.75rem",
                "--sidebar": "#ffffff",
                "--sidebar-foreground": "#160b2e",
                "--sidebar-primary": "#6d28d9",
                "--sidebar-primary-foreground": "#ffffff",
                "--sidebar-accent": "#f5f3ff",
                "--sidebar-accent-foreground": "#160b2e",
                "--sidebar-border": "#e4e4e7",
                "--sidebar-ring": "#6d28d9",
            },
            dark: {
                "--background": "#050011",
                "--foreground": "#ede9fe",
                "--card": "#0a041a",
                "--card-foreground": "#ede9fe",
                "--popover": "#0a041a",
                "--popover-foreground": "#ede9fe",
                "--primary": "#8b5cf6",
                "--primary-foreground": "#050011",
                "--secondary": "#1c103f",
                "--secondary-foreground": "#ede9fe",
                "--muted": "#1c103f",
                "--muted-foreground": "#a1a1aa",
                "--accent": "#6d28d9",
                "--accent-foreground": "#ede9fe",
                "--destructive": "#dc2626",
                "--success": "#064e3b",
                "--warning": "#78350f",
                "--border": "#1c103f",
                "--input": "#1c103f",
                "--ring": "#8b5cf6",
                "--radius": "0.75rem",
                "--sidebar": "#0a041a",
                "--sidebar-foreground": "#ede9fe",
                "--sidebar-primary": "#8b5cf6",
                "--sidebar-primary-foreground": "#050011",
                "--sidebar-accent": "#1c103f",
                "--sidebar-accent-foreground": "#ede9fe",
                "--sidebar-border": "#1c103f",
                "--sidebar-ring": "#8b5cf6",
            }
        }
    },
    [THEME_IDS.FOREST_AMBER]: {
        name: "Forest Amber",
        tier: "pro",
        mode: {
            light: {
                "--background": "#f7f9f2",
                "--foreground": "#1a2416",
                "--card": "#ffffff",
                "--card-foreground": "#1a2416",
                "--popover": "#ffffff",
                "--popover-foreground": "#1a2416",
                "--primary": "#4a7c2e",
                "--primary-foreground": "#ffffff",
                "--secondary": "#e8f0e0",
                "--secondary-foreground": "#1a2416",
                "--muted": "#edf3e6",
                "--muted-foreground": "#5e7052",
                "--accent": "#d97706",
                "--accent-foreground": "#ffffff",
                "--destructive": "#ef4444",
                "--success": "#22c55e",
                "--warning": "#eab308",
                "--border": "#dce5d0",
                "--input": "#dce5d0",
                "--ring": "#4a7c2e",
                "--radius": "0.5rem",
                "--sidebar": "#ffffff",
                "--sidebar-foreground": "#1a2416",
                "--sidebar-primary": "#4a7c2e",
                "--sidebar-primary-foreground": "#ffffff",
                "--sidebar-accent": "#f0f5e8",
                "--sidebar-accent-foreground": "#1a2416",
                "--sidebar-border": "#dce5d0",
                "--sidebar-ring": "#4a7c2e",
            },
            dark: {
                "--background": "#0a1208",
                "--foreground": "#e8f0e0",
                "--card": "#111c0e",
                "--card-foreground": "#e8f0e0",
                "--popover": "#111c0e",
                "--popover-foreground": "#e8f0e0",
                "--primary": "#80b350",
                "--primary-foreground": "#0a1208",
                "--secondary": "#1a2e14",
                "--secondary-foreground": "#e8f0e0",
                "--muted": "#1a2e14",
                "--muted-foreground": "#8fa086",
                "--accent": "#f59e0b",
                "--accent-foreground": "#0a1208",
                "--destructive": "#dc2626",
                "--success": "#14532d",
                "--warning": "#854d0e",
                "--border": "#1a2e14",
                "--input": "#1a2e14",
                "--ring": "#80b350",
                "--radius": "0.5rem",
                "--sidebar": "#111c0e",
                "--sidebar-foreground": "#e8f0e0",
                "--sidebar-primary": "#80b350",
                "--sidebar-primary-foreground": "#0a1208",
                "--sidebar-accent": "#1a2e14",
                "--sidebar-accent-foreground": "#e8f0e0",
                "--sidebar-border": "#1a2e14",
                "--sidebar-ring": "#80b350",
            }
        }
    },
    [THEME_IDS.ROSE_QUARTZ]: {
        name: "Rose Quartz",
        tier: "pro",
        mode: {
            light: {
                "--background": "#fff5f7",
                "--foreground": "#4a0519",
                "--card": "#ffffff",
                "--card-foreground": "#4a0519",
                "--popover": "#ffffff",
                "--popover-foreground": "#4a0519",
                "--primary": "#e11d48",
                "--primary-foreground": "#ffffff",
                "--secondary": "#ffe6ea",
                "--secondary-foreground": "#4a0519",
                "--muted": "#fff0f3",
                "--muted-foreground": "#9f5a6b",
                "--accent": "#be123c",
                "--accent-foreground": "#ffffff",
                "--destructive": "#ef4444",
                "--success": "#10b981",
                "--warning": "#f59e0b",
                "--border": "#fecdd3",
                "--input": "#fecdd3",
                "--ring": "#e11d48",
                "--radius": "1rem",
                "--sidebar": "#ffffff",
                "--sidebar-foreground": "#4a0519",
                "--sidebar-primary": "#e11d48",
                "--sidebar-primary-foreground": "#ffffff",
                "--sidebar-accent": "#fff0f3",
                "--sidebar-accent-foreground": "#4a0519",
                "--sidebar-border": "#fecdd3",
                "--sidebar-ring": "#e11d48",
            },
            dark: {
                "--background": "#1a0008",
                "--foreground": "#fff0f3",
                "--card": "#2d0012",
                "--card-foreground": "#fff0f3",
                "--popover": "#2d0012",
                "--popover-foreground": "#fff0f3",
                "--primary": "#fb7185",
                "--primary-foreground": "#1a0008",
                "--secondary": "#5c001b",
                "--secondary-foreground": "#fff0f3",
                "--muted": "#5c001b",
                "--muted-foreground": "#fda4af",
                "--accent": "#9f1239",
                "--accent-foreground": "#ffffff",
                "--destructive": "#7f1d1d",
                "--success": "#064e3b",
                "--warning": "#78350f",
                "--border": "#5c001b",
                "--input": "#5c001b",
                "--ring": "#fb7185",
                "--radius": "1rem",
                "--sidebar": "#2d0012",
                "--sidebar-foreground": "#fff0f3",
                "--sidebar-primary": "#fb7185",
                "--sidebar-primary-foreground": "#1a0008",
                "--sidebar-accent": "#5c001b",
                "--sidebar-accent-foreground": "#fff0f3",
                "--sidebar-border": "#5c001b",
                "--sidebar-ring": "#fb7185",
            }
        }
    },
    [THEME_IDS.COFFEE]: {
        name: "Coffee",
        tier: "pro",
        mode: {
            light: {
                "--background": "#fdf8f0",
                "--foreground": "#3b2a1f",
                "--card": "#ffffff",
                "--card-foreground": "#3b2a1f",
                "--popover": "#ffffff",
                "--popover-foreground": "#3b2a1f",
                "--primary": "#8b5a2b",
                "--primary-foreground": "#ffffff",
                "--secondary": "#f5e6d3",
                "--secondary-foreground": "#3b2a1f",
                "--muted": "#faf0e6",
                "--muted-foreground": "#8a6e4b",
                "--accent": "#c77d3e",
                "--accent-foreground": "#ffffff",
                "--destructive": "#ef4444",
                "--success": "#10b981",
                "--warning": "#f59e0b",
                "--border": "#e6d5c0",
                "--input": "#e6d5c0",
                "--ring": "#8b5a2b",
                "--radius": "0.5rem",
                "--sidebar": "#ffffff",
                "--sidebar-foreground": "#3b2a1f",
                "--sidebar-primary": "#8b5a2b",
                "--sidebar-primary-foreground": "#ffffff",
                "--sidebar-accent": "#fdf8f0",
                "--sidebar-accent-foreground": "#3b2a1f",
                "--sidebar-border": "#e6d5c0",
                "--sidebar-ring": "#8b5a2b",
            },
            dark: {
                "--background": "#1a120b",
                "--foreground": "#f5e6d3",
                "--card": "#2a1e14",
                "--card-foreground": "#f5e6d3",
                "--popover": "#2a1e14",
                "--popover-foreground": "#f5e6d3",
                "--primary": "#b8823a",
                "--primary-foreground": "#1a120b",
                "--secondary": "#3a2a1a",
                "--secondary-foreground": "#f5e6d3",
                "--muted": "#3a2a1a",
                "--muted-foreground": "#b8956e",
                "--accent": "#e8913e",
                "--accent-foreground": "#1a120b",
                "--destructive": "#dc2626",
                "--success": "#064e3b",
                "--warning": "#78350f",
                "--border": "#3a2a1a",
                "--input": "#3a2a1a",
                "--ring": "#b8823a",
                "--radius": "0.5rem",
                "--sidebar": "#2a1e14",
                "--sidebar-foreground": "#f5e6d3",
                "--sidebar-primary": "#b8823a",
                "--sidebar-primary-foreground": "#1a120b",
                "--sidebar-accent": "#3a2a1a",
                "--sidebar-accent-foreground": "#f5e6d3",
                "--sidebar-border": "#3a2a1a",
                "--sidebar-ring": "#b8823a",
            }
        }
    },
    [THEME_IDS.SAKURA]: {
        name: "Sakura",
        tier: "pro",
        mode: {
            light: {
                "--background": "#fff5f9",
                "--foreground": "#4a2c3a",
                "--card": "#ffffff",
                "--card-foreground": "#4a2c3a",
                "--popover": "#ffffff",
                "--popover-foreground": "#4a2c3a",
                "--primary": "#f48fb1",
                "--primary-foreground": "#4a2c3a",
                "--secondary": "#ffe0e8",
                "--secondary-foreground": "#4a2c3a",
                "--muted": "#fff0f5",
                "--muted-foreground": "#8a6e7a",
                "--accent": "#f06292",
                "--accent-foreground": "#ffffff",
                "--destructive": "#ef4444",
                "--success": "#10b981",
                "--warning": "#f59e0b",
                "--border": "#fce4ec",
                "--input": "#fce4ec",
                "--ring": "#f48fb1",
                "--radius": "1rem",
                "--sidebar": "#ffffff",
                "--sidebar-foreground": "#4a2c3a",
                "--sidebar-primary": "#f48fb1",
                "--sidebar-primary-foreground": "#4a2c3a",
                "--sidebar-accent": "#fff5f9",
                "--sidebar-accent-foreground": "#4a2c3a",
                "--sidebar-border": "#fce4ec",
                "--sidebar-ring": "#f48fb1",
            },
            dark: {
                "--background": "#1e1218",
                "--foreground": "#ffe0e8",
                "--card": "#2e1a24",
                "--card-foreground": "#ffe0e8",
                "--popover": "#2e1a24",
                "--popover-foreground": "#ffe0e8",
                "--primary": "#ff80ab",
                "--primary-foreground": "#1e1218",
                "--secondary": "#4a2c3a",
                "--secondary-foreground": "#ffe0e8",
                "--muted": "#4a2c3a",
                "--muted-foreground": "#cc9aaa",
                "--accent": "#ff4081",
                "--accent-foreground": "#1e1218",
                "--destructive": "#7f1d1d",
                "--success": "#064e3b",
                "--warning": "#78350f",
                "--border": "#4a2c3a",
                "--input": "#4a2c3a",
                "--ring": "#ff80ab",
                "--radius": "1rem",
                "--sidebar": "#2e1a24",
                "--sidebar-foreground": "#ffe0e8",
                "--sidebar-primary": "#ff80ab",
                "--sidebar-primary-foreground": "#1e1218",
                "--sidebar-accent": "#4a2c3a",
                "--sidebar-accent-foreground": "#ffe0e8",
                "--sidebar-border": "#4a2c3a",
                "--sidebar-ring": "#ff80ab",
            }
        }
    },
    [THEME_IDS.PLATINUM]: {
        name: "Platinum",
        tier: "pro",
        mode: {
            light: {
                "--background": "#f5f7fa",
                "--foreground": "#1a202c",
                "--card": "#ffffff",
                "--card-foreground": "#1a202c",
                "--popover": "#ffffff",
                "--popover-foreground": "#1a202c",
                "--primary": "#4a5568",
                "--primary-foreground": "#ffffff",
                "--secondary": "#e2e8f0",
                "--secondary-foreground": "#1a202c",
                "--muted": "#edf2f7",
                "--muted-foreground": "#718096",
                "--accent": "#6b7280",
                "--accent-foreground": "#ffffff",
                "--destructive": "#ef4444",
                "--success": "#10b981",
                "--warning": "#f59e0b",
                "--border": "#cbd5e0",
                "--input": "#cbd5e0",
                "--ring": "#4a5568",
                "--radius": "0.375rem",
                "--sidebar": "#ffffff",
                "--sidebar-foreground": "#1a202c",
                "--sidebar-primary": "#4a5568",
                "--sidebar-primary-foreground": "#ffffff",
                "--sidebar-accent": "#f5f7fa",
                "--sidebar-accent-foreground": "#1a202c",
                "--sidebar-border": "#cbd5e0",
                "--sidebar-ring": "#4a5568",
            },
            dark: {
                "--background": "#0f1419",
                "--foreground": "#e2e8f0",
                "--card": "#1a202c",
                "--card-foreground": "#e2e8f0",
                "--popover": "#1a202c",
                "--popover-foreground": "#e2e8f0",
                "--primary": "#94a3b8",
                "--primary-foreground": "#0f1419",
                "--secondary": "#2d3748",
                "--secondary-foreground": "#e2e8f0",
                "--muted": "#2d3748",
                "--muted-foreground": "#a0aec0",
                "--accent": "#718096",
                "--accent-foreground": "#e2e8f0",
                "--destructive": "#dc2626",
                "--success": "#064e3b",
                "--warning": "#78350f",
                "--border": "#2d3748",
                "--input": "#2d3748",
                "--ring": "#94a3b8",
                "--radius": "0.375rem",
                "--sidebar": "#1a202c",
                "--sidebar-foreground": "#e2e8f0",
                "--sidebar-primary": "#94a3b8",
                "--sidebar-primary-foreground": "#0f1419",
                "--sidebar-accent": "#2d3748",
                "--sidebar-accent-foreground": "#e2e8f0",
                "--sidebar-border": "#2d3748",
                "--sidebar-ring": "#94a3b8",
            }
        }
    },
    [THEME_IDS.ROYAL_NEBULA]: {
        name: "Royal Nebula",
        tier: "pro",
        mode: {
            light: {
                "--background": "#f8f4ff",
                "--foreground": "#1e1b4b",
                "--card": "#ffffff",
                "--card-foreground": "#1e1b4b",
                "--popover": "#ffffff",
                "--popover-foreground": "#1e1b4b",
                "--primary": "#6d28d9",
                "--primary-foreground": "#ffffff",
                "--secondary": "#ede9fe",
                "--secondary-foreground": "#1e1b4b",
                "--muted": "#f5f3ff",
                "--muted-foreground": "#8b5cf6",
                "--accent": "#7c3aed",
                "--accent-foreground": "#ffffff",
                "--destructive": "#ef4444",
                "--success": "#10b981",
                "--warning": "#f59e0b",
                "--border": "#e0d4ff",
                "--input": "#e0d4ff",
                "--ring": "#7c3aed",
                "--radius": "0.75rem",
                "--sidebar": "#ffffff",
                "--sidebar-foreground": "#1e1b4b",
                "--sidebar-primary": "#7c3aed",
                "--sidebar-primary-foreground": "#ffffff",
                "--sidebar-accent": "#f8f4ff",
                "--sidebar-accent-foreground": "#1e1b4b",
                "--sidebar-border": "#e0d4ff",
                "--sidebar-ring": "#7c3aed",
            },
            dark: {
                "--background": "#0b0a1a",
                "--foreground": "#e9d5ff",
                "--card": "#14122e",
                "--card-foreground": "#e9d5ff",
                "--popover": "#14122e",
                "--popover-foreground": "#e9d5ff",
                "--primary": "#a78bfa",
                "--primary-foreground": "#0b0a1a",
                "--secondary": "#2e1a6b",
                "--secondary-foreground": "#e9d5ff",
                "--muted": "#2e1a6b",
                "--muted-foreground": "#c4b5fd",
                "--accent": "#8b5cf6",
                "--accent-foreground": "#ffffff",
                "--destructive": "#dc2626",
                "--success": "#064e3b",
                "--warning": "#78350f",
                "--border": "#3a2a7a",
                "--input": "#3a2a7a",
                "--ring": "#a78bfa",
                "--radius": "0.75rem",
                "--sidebar": "#14122e",
                "--sidebar-foreground": "#e9d5ff",
                "--sidebar-primary": "#a78bfa",
                "--sidebar-primary-foreground": "#0b0a1a",
                "--sidebar-accent": "#2e1a6b",
                "--sidebar-accent-foreground": "#e9d5ff",
                "--sidebar-border": "#3a2a7a",
                "--sidebar-ring": "#a78bfa",
            }
        }
    }
};